/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.teamvietdev.qlhv.view;

import com.teamvietdev.qlhv.controller.QuanLyKhoaAIController;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class KhoaAIJPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhoaAIJPanel
     */
    public KhoaAIJPanel() {
        initComponents();
        QuanLyKhoaAIController controller = new QuanLyKhoaAIController(jPanelViewAI, jbtAddAI, jTextSearchAI,jbtRefreshAI,jbtDeleteAI);
        controller.setDataToTable();
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtAddAI = new javax.swing.JButton();
        jTextSearchAI = new javax.swing.JTextField();
        jbtRefreshAI = new javax.swing.JButton();
        jbtDeleteAI = new javax.swing.JButton();
        jPanelViewAI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(793, 624));

        jbtAddAI.setBackground(new java.awt.Color(76, 175, 80));
        jbtAddAI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtAddAI.setForeground(new java.awt.Color(255, 255, 255));
        jbtAddAI.setText("Thêm mới");
        jbtAddAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddAIActionPerformed(evt);
            }
        });

        jTextSearchAI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jbtRefreshAI.setBackground(new java.awt.Color(51, 102, 255));
        jbtRefreshAI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtRefreshAI.setForeground(new java.awt.Color(255, 255, 255));
        jbtRefreshAI.setText("Refresh");

        jbtDeleteAI.setBackground(new java.awt.Color(255, 51, 51));
        jbtDeleteAI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtDeleteAI.setForeground(new java.awt.Color(255, 255, 255));
        jbtDeleteAI.setText("Xóa");

        javax.swing.GroupLayout jPanelViewAILayout = new javax.swing.GroupLayout(jPanelViewAI);
        jPanelViewAI.setLayout(jPanelViewAILayout);
        jPanelViewAILayout.setHorizontalGroup(
            jPanelViewAILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelViewAILayout.setVerticalGroup(
            jPanelViewAILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setText("Khóa AI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelViewAI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextSearchAI, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtRefreshAI, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jbtDeleteAI, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jbtAddAI, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtAddAI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtRefreshAI, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(jbtDeleteAI, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(jTextSearchAI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanelViewAI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAddAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddAIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtAddAIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelViewAI;
    private javax.swing.JTextField jTextSearchAI;
    private javax.swing.JButton jbtAddAI;
    private javax.swing.JButton jbtDeleteAI;
    private javax.swing.JButton jbtRefreshAI;
    // End of variables declaration//GEN-END:variables
}
