package com.teamvietdev.qlhv.view;

import com.teamvietdev.qlhv.controller.QuanLyTaiKhoanController;

/**
 *
 * @author ADMIN
 */
public class TaoTKJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TaoTKJPanel
     */
    public TaoTKJPanel() {
        initComponents();
        
        QuanLyTaiKhoanController controller = new QuanLyTaiKhoanController(jpnViewTK, btnAddTK, btnXoaTK,btnRefreshTK,jtfSearchTK);
        controller.setDataToTable();
        controller.setEvent();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jtfSearchTK = new javax.swing.JTextField();
        jpnViewTK = new javax.swing.JPanel();
        btnXoaTK = new javax.swing.JButton();
        btnRefreshTK = new javax.swing.JButton();
        btnAddTK = new javax.swing.JButton();

        javax.swing.GroupLayout jpnViewTKLayout = new javax.swing.GroupLayout(jpnViewTK);
        jpnViewTK.setLayout(jpnViewTKLayout);
        jpnViewTKLayout.setHorizontalGroup(
            jpnViewTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnViewTKLayout.setVerticalGroup(
            jpnViewTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        btnXoaTK.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaTK.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnXoaTK.setText("Xóa");

        btnRefreshTK.setBackground(new java.awt.Color(153, 255, 255));
        btnRefreshTK.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRefreshTK.setText("Refresh");
        btnRefreshTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTKActionPerformed(evt);
            }
        });

        btnAddTK.setBackground(new java.awt.Color(76, 175, 80));
        btnAddTK.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAddTK.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTK.setText("+ Thêm mới");

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addComponent(jtfSearchTK, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefreshTK, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnXoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnAddTK, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnViewTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfSearchTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaTK, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnRefreshTK, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnAddTK, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnViewTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshTKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTK;
    private javax.swing.JButton btnRefreshTK;
    private javax.swing.JButton btnXoaTK;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnViewTK;
    private javax.swing.JTextField jtfSearchTK;
    // End of variables declaration//GEN-END:variables
}
